### ISSUE TITLE
Search campaigns returns "Invalid type for variable 'value'" when it is null

### ISSUE THREAD

**Issue by 4ndt3s** [criteo/criteo-api-python-sdk#6]
**Version:** v2022_04
**Endpoint:** marketing-solutions/campaigns/search
**Problem:** 
Using Postman to fetch the campaigns search endpoint returns:
```
{
    "data": [
        {
            "id": "123456",
            "type": "Campaign",
            "attributes": {
                "name": "A name",
                "advertiserId": "54321",
                "objective": "CatalogSales",
                "spendLimit": {
                    "spendLimitType": "uncapped",
                    "spendLimitRenewal": "undefined",
                    "spendLimitAmount": {
                        "value": null
                    }
                }
            }
        }
    ]
}
```  
  
When the same endpoint is fetched with the SDK it returns:

`ApiTypeError: Invalid type for variable 'value'. Required value type is float and passed type was NoneType at ['received_data']['data'][0]['attributes']['spend_limit']['spend_limit_amount']['value']`

**Comment by 4ndt3s** [comment]
A similar problem when searching adsets, if the end time is null the SDK returns:  

`ApiTypeError: Invalid type for variable 'value'. Required value type is datetime and passed type was NoneType at ['received_data']['data'][0]['attributes']['schedule']['end_date']['value']`

**Comment by manualaman5** [comment]
Hello,

I am blocked by this issue. I see that there has been a merge with the fix, but it hasn't been released. Do you have an ETA for this release?

Thanks,
Manu

**Comment by 4ndt3s** [comment]
Hi @PaulMathon, thank you for your response.

I am also waiting for this fix to be reflected in the SDK.

Regards.

**Comment by PaulMathon** [comment]
Hi all, 
The fix has been released on 06/22/2022 🎉. To use it please install the package's latest version (**2022.04.0.220624** for Criteo API version 2022-04).
Let me know if you have any further questions.
Thank you.

**Comment by 4ndt3s** [comment]
Hi @PaulMathon 

I have tested the updated package. The problem is fixed when searching campaigns, but it persists when searching ad sets:  
```
ApiTypeError: Invalid type for variable 'bid_amount'. Required value type is NillableDecimal and passed type was NoneType at ['received_data']['data'][0]['attributes']['bidding']['bid_amount']
```
